# FROM UDI Latest
FROM registry.redhat.io/devspaces/udi-rhel9:latest

USER root

# 1. Add AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws/

# 2. Add Azure CLI & PowerShell
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    dnf install -y https://packages.microsoft.com/config/rhel/9.0/packages-microsoft-prod.rpm && \
    dnf install -y azure-cli powershell && \
    dnf clean all

# 3. Install Azure Powershell (Fixing the previous shell error)
RUN pwsh -Command "Install-Module -Name Az -Repository PSGallery -Force -Scope AllUsers"

# 4. Add Helm CLI
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && \
    chmod 700 get_helm.sh && \
    ./get_helm.sh && \
    rm get_helm.sh

# 5. Add ROSA CLI (with ownership fix)
RUN curl -L "https://developers.redhat.com/content-gateway/file/pub/cgw/rosa/1.2.61/rosa-linux.tar.gz" -o "rosa-linux.tar.gz" && \
    tar -xvf rosa-linux.tar.gz --no-same-owner && \
    mv rosa /usr/local/bin/rosa && \
    chmod +x /usr/local/bin/rosa && \
    rm rosa-linux.tar.gz

USER 1001